name: Validate Production Pull Request
 
on: 
  pull_request:
    branches:
      - main
    paths:
      - 'force-app/**'
 
jobs:
  validate:
    runs-on: ubuntu-latest  # Fixed typo: was "unbuntu-latest"
    steps:
      - uses: actions/checkout@v3  # Fixed typo: was "checout"
      - name: Validate on Production
        uses: jawills/sf-deploy@v1.0
        with: 
          SFDX_AUTH_URL: ${{ secrets.SFDX_AUTH_URL }}  # Fixed typo: was "screts"

          DRY_RUN: true

